import { AppSchema, column, Table } from '@powersync/react-native';

export const schema = new AppSchema({
  user_equipment: new Table({
    user_id: column.text,
    equipment: column.text,
    created_at: column.text,
    updated_at: column.text,
  }),
  exercises: new Table({
    name: column.text,
    name_ru: column.text,
    muscle_group: column.text,
    equipment: column.text,
    difficulty: column.integer,
    set_type: column.text,
    instructions: column.text,
    progression_of: column.text,
    is_custom: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  workout_templates: new Table({
    user_id: column.text,
    name: column.text,
    description: column.text,
    split_type: column.text,
    is_generated: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  template_exercises: new Table({
    template_id: column.text,
    exercise_id: column.text,
    order_index: column.integer,
    default_sets: column.integer,
    default_reps: column.integer,
    default_time_s: column.integer,
    rest_seconds: column.integer,
    created_at: column.text,
  }),
  workouts: new Table({
    user_id: column.text,
    template_id: column.text,
    name: column.text,
    note: column.text,
    started_at: column.text,
    finished_at: column.text,
    duration_s: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  workout_sets: new Table({
    workout_id: column.text,
    exercise_id: column.text,
    set_number: column.integer,
    weight_kg: column.real,
    reps: column.integer,
    time_s: column.integer,
    band_level: column.text,
    is_warmup: column.integer,
    completed: column.integer,
    completed_at: column.text,
    note: column.text,
    created_at: column.text,
    updated_at: column.text,
  }),
  user_settings: new Table({
    user_id: column.text,
    value: column.text,
    updated_at: column.text,
  }),
  nutrition_logs: new Table({
    user_id: column.text,
    date: column.text,
    meal_type: column.text,
    food_name: column.text,
    calories: column.integer,
    protein_g: column.real,
    fat_g: column.real,
    carbs_g: column.real,
    created_at: column.text,
    updated_at: column.text,
  }),
  body_metrics: new Table({
    user_id: column.text,
    date: column.text,
    weight_kg: column.real,
    body_fat_pct: column.real,
    muscle_mass_kg: column.real,
    water_pct: column.real,
    chest_cm: column.real,
    waist_cm: column.real,
    hips_cm: column.real,
    arms_cm: column.real,
    legs_cm: column.real,
    calves_cm: column.real,
    shoulders_cm: column.real,
    neck_cm: column.real,
    created_at: column.text,
    updated_at: column.text,
  }),
});
